spring:
  datasource:
    url: ${nyangmunity.dev-mysql-url}
    username: ${nyangmunity.dev-mysql-username}
    password: ${nyangmunity.dev-mysql-password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ${upstash.dev-redis-host}
      port: ${upstash.dev-redis-port}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

# 개발 환경 로깅 레벨
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web: DEBUG

# 개발 환경 변수
nyangmunity:
  domain: localhost
  cookie-secure: false # localhost(HTTP) 에서도 쿠키가 박히도록 dev 만 false
jwt:
  access-token-expiration: 3600000 # 1시간
  refresh-token-expiration: 2592000000 # 30일
kakao:
  redirect-uri: "http://localhost:5173/auth/kakao/callback"
google:
  redirect-uri: "http://localhost:5173/auth/google/callback"