spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nyangmunity?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: jdg3572
  servlet:
    multipart:
      location: C:\Users\ppusd\Pictures\NyangMunityImages