server:
  port: 8080

spring:
  profiles:
    active: dev
  config:
    import: classpath:application-secret.yml
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    database: mysql
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0
  mustache:
    suffix: .html
    prefix: classpath:/static/

logging:
  level:
    org.springframework.web: DEBUG
nyangmunity:
  jwt-key: ${custom.jwt-secret-key}

kakao:
  client-key: ${custom.kakao-client-key}
  secret-key: ${custom.kakao-secret-key}
  grant-type: ${custom.kakao-grant-type}
