spring:
  config:
    import: classpath:application-secret.yml
  datasource:
    url: ${nyangmunity.dev-mysql-url}
    username: ${nyangmunity.dev-mysql-username}
    password: ${nyangmunity.dev-mysql-password}
  jpa:
    hibernate:
      ddl-auto: update

nyangmunity:
  domain: localhost

jwt:
  access-token-expiration: 900000 # 15분
  refresh-token-expiration: 10800000 # 3시간

kakao:
  redirect-uri: "http://localhost:5173/auth/kakao/callback"

google:
  redirect-uri: "http://localhost:5173/auth/google/callback"