spring:
  profiles:
    active: dev
  config:
    import: classpath:application-secret.yml
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5
  batch:
    job:
      enabled: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 0

logging:
  level:
    org.springframework.web: DEBUG