### 로그인 요청

POST http://localhost:8080/nm/user/login
Content-Type: application/json

{
  "email": "ppusda@naver.com",
  "password": "1234"
}

### 인증 페이지 요청

GET http://localhost:8080/nm/test
Content-Type: application/json
#Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0MiJ9.VgnbXwnnMsY5IC_SQCGrgaTmtyeDaG-6Nc9KypnHNHc
Cookie: SID=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI0MiJ9.VgnbXwnnMsY5IC_SQCGrgaTmtyeDaG-6Nc9KypnHNHc